Repository mage2click/docker-magento-mutagen, pull requests merged in 2019-06, with the labels that each got.

#60 Fixed bug with custom xdebug settings not applied after bin/setup/xdebug
  README.md
  compose/magento-2/bin/setup/templates/.user.ini.sample
  compose/magento-2/bin/setup/xdebug
Labels: 2.x.x, Xdebug, bug

#62 Added changes to avoid downloading images if the latest version is used
  compose/magento-2/bin/update
Labels: 2.x.x, bug, devops, enhancement

#64 GH-61 Fixed bug reported by CNanninga
  compose/magento-2/bin/dbimport
Labels: 2.x.x, bug, devops, mysql

#65 Update README.md
  README.md
Labels: 2.x.x, doc-update

#67 Feature/update md files
  README.md
Labels: 2.x.x, doc-update

#63 Feature/mutagen 0.9 update
  README.md
  compose/magento-2/bin/composer
  compose/magento-2/bin/mutagen
  compose/magento-2/bin/start
  compose/magento-2/bin/update
  lib/setup
Labels: 2.x.x, doc-update, enhancement, mutagen.io, sync-config

#69 Feature/use volume for elasticsearch
  compose/magento-2/docker-compose.yml.sample
  compose/magento-2/parts/elasticsearch/2.4.yml
  compose/magento-2/parts/elasticsearch/5.6.yml
  compose/magento-2/parts/elasticsearch/6.7.2.yml
  compose/magento-2/parts/volumes/default.yml
  compose/magento-2/parts/volumes/elasticsearch.yml
  lib/setup
Labels: 2.x.x, Elasticsearch, devops, enhancement

#70 Removed --scan-mode=accelerated param
  compose/magento-2/bin/mutagen
Labels: 2.x.x, bug, devops, mutagen.io, sync-config

#71 Moved creating of the nginx.conf file
  compose/magento-2/bin/setup/start
Labels: 2.x.x, Magento Cloud, bug, devops

#72 Updated .gitignore files
  .gitignore
  compose/magento-2/.gitignore
Labels: 2.x.x, bug, devops

#73 Suppress errors if folders var, pub, app does not exist during setup.
  compose/magento-2/bin/setup/start
Labels: 2.x.x, bug, devops

#74 Bugfix/fix magento cloud install
  compose/magento-2/bin/setup/start
Labels: 2.x.x, bug, devops

#75 Bugfix/fix magento cloud install
  compose/magento-2/bin/mutagen
Labels: 2.x.x, bug, devops, mutagen.io, sync-config

#76 Execute "cp nginx.conf.sample to nginx.conf" command inside the container
  compose/magento-2/bin/setup/start
Labels: 2.x.x, bug, devops

#77 Improved logic of copying files after composer
  compose/magento-2/bin/setup/start
Labels: 2.x.x, bug, devops

#79 Added fix to actually press any key to continue and not just Enter key
  lib/setup
Labels: 2.x.x, bug, devops

#80 Feature/share
  README.md
  compose/magento-2/bin/setup/share
  compose/magento-2/bin/share
  compose/magento-2/parts/app/default.yml
  compose/magento-2/parts/app/varnish.yml
Labels: 2.x.x, devops, doc-update, enhancement

#81 Added a notice about `magento-nginx:1.15-alpine` update for existing setups
  README.md
Labels: 2.x.x, devops, doc-update

#82 Added fix to get working ngrok web Interface link
  compose/magento-2/bin/share
Labels: 2.x.x, bug, devops

#83 Bugfix/dev urn catalog generate
  compose/magento-2/bin/dev-urn-catalog-generate
Labels: 2.x.x, bug, devops, enhancement
