Repository mage2click/docker-magento-mutagen, pull requests merged in 2019-05, with the labels that each got.

#4 Added Varnish v4.1, installed and configured out of the box
  README.md
  compose/magento-2/bin/magento-configure-varnish
  compose/magento-2/bin/setup
  compose/magento-2/bin/setup-lite
  compose/magento-2/docker-compose.yml
Labels: devops, enhancement, varnish:4.1

#5 Added Elasticsearch 5 as Search Engine out of the box
  README.md
  compose/magento-2/bin/magento-configure-elasticsearh5
  compose/magento-2/bin/setup
  compose/magento-2/bin/setup-lite
Labels: Elasticsearch:5, devops, enhancement

#35 Updated yml templates to use mage2click/magento-elasticsearch
  README.md
  compose/magento-2/bin/setup/elasticsearch
  compose/magento-2/bin/setup/start
  compose/magento-2/docker-compose.yml.sample
  compose/magento-2/parts/elasticsearch/2.4.yml
  compose/magento-2/parts/elasticsearch/5.6.yml
  compose/magento-2/parts/elasticsearch/6.7.2.yml
Labels: Elasticsearch, devops, enhancement

#42 GH-40 Replaced percona:5.7 with mariadb:10.2. Updated README
  README.md
  compose/magento-2/parts/db.yml
Labels: 2.x.x, enhancement, mysql

#45 GH-44 Changed php images to use new repo
  README.md
  compose/magento-2/docker-compose.yml.sample
  compose/magento-2/parts/cron/7.0.yml
  compose/magento-2/parts/cron/7.1.yml
  compose/magento-2/parts/cron/7.2.yml
  compose/magento-2/parts/phpfpm/7.0-mailhog.yml
  compose/magento-2/parts/phpfpm/7.0.yml
  compose/magento-2/parts/phpfpm/7.1-mailhog.yml
  compose/magento-2/parts/phpfpm/7.1.yml
  compose/magento-2/parts/phpfpm/7.2-mailhog.yml
  compose/magento-2/parts/phpfpm/7.2.yml
Labels: 2.x.x, PHP-images, enhancement

#46 Implemented new mutagen session which will sync "/var/www/.composer/"…
  compose/magento-2/bin/mutagen
  compose/magento-2/docker-compose.yml.sample
  compose/magento-2/parts/app/default.yml
  compose/magento-2/parts/app/varnish.yml
Labels: 2.x.x, composer, devops, enhancement, mutagen.io

#43 Added bin/restart-nginx command. Updated README
  README.md
  compose/magento-2/bin/restart-nginx
Labels: 2.x.x, devops, enhancement

#47 Feature/restart of specific container
  README.md
  compose/magento-2/bin/restart
  compose/magento-2/bin/restart-nginx
  compose/magento-2/bin/setup/start
Labels: 2.x.x, devops, enhancement

#48 Restart only phpfpm container after enabling/disabling xdebug
  compose/magento-2/bin/xdebug
Labels: 2.x.x, bug, devops

#49 Fixed bin/bash to allow running from anywhere and to pass along any a…
  compose/magento-2/bin/bash
Labels: 2.x.x, devops, enhancement

#50 Revert "Implemented new mutagen session which will sync "/var/www/.composer/"…"
  compose/magento-2/bin/mutagen
  compose/magento-2/docker-compose.yml.sample
  compose/magento-2/parts/app/default.yml
  compose/magento-2/parts/app/varnish.yml
Labels: 2.x.x, bug, devops, mutagen.io

#51 Feature/mariadb 10:3
  README.md
  compose/magento-2/parts/db.yml
Labels: 2.x.x, MariaDB, enhancement, mysql

#55 Feature/self update improvement
  README.md
  compose/magento-2/bin/update
Labels: 2.x.x, devops, enhancement, mutagen.io

#52 Added env/_config to configure location of synced "src" directory
  compose/magento-2/bin/copyfromcontainer
  compose/magento-2/bin/copytocontainer
  compose/magento-2/bin/dev-urn-catalog-generate
  compose/magento-2/bin/mutagen
  compose/magento-2/bin/setup/import
  compose/magento-2/bin/setup/start
  compose/magento-2/bin/setup/varnish
  compose/magento-2/env/_config
Labels: 2.x.x, devops, enhancement

#56 Bugfix/env config src
  compose/magento-2/bin/copyfromcontainer
  compose/magento-2/bin/copytocontainer
  compose/magento-2/bin/dev-urn-catalog-generate
  compose/magento-2/bin/mutagen
  compose/magento-2/bin/setup/import
  compose/magento-2/bin/setup/start
  compose/magento-2/bin/setup/varnish
  compose/magento-2/bin/update
Labels: 2.x.x, bug, devops

#53 Added new commands for setting up xdebug on phpfpm container side.
  README.md
  compose/magento-2/bin/setup/templates/.user.ini.sample
  compose/magento-2/bin/setup/xdebug
  compose/magento-2/parts/phpfpm/7.0-mailhog.yml
  compose/magento-2/parts/phpfpm/7.0.yml
  compose/magento-2/parts/phpfpm/7.1-mailhog.yml
  compose/magento-2/parts/phpfpm/7.1.yml
  compose/magento-2/parts/phpfpm/7.2-mailhog.yml
  compose/magento-2/parts/phpfpm/7.2.yml
  lib/setup
Labels: 2.x.x, PHP-images, Xdebug, devops, doc-update, enhancement

#54 Updated SETUP.md, CHANGELOG.md and README.md with new info and links …
  CHANGELOG.md
  README.md
  SETUP.md
Labels: 2.x.x, doc-update

#58 Bugfix/copy command
  compose/magento-2/bin/copyfromcontainer
  compose/magento-2/bin/copytocontainer
Labels: 2.x.x, bug, devops
